### ISSUE TITLE
Fatal error:  Uncaught Error: Call to a member function format() on bool

### ISSUE THREAD

**Issue by nadirnasir** [SergiX44/php-benchmark-script#5]
Hi, getting Fatal error:  Uncaught Error: Call to a member function format() on bool when trying to run the script. Screenshot attached. 

![image](https://github.com/sergix44/php-benchmark-script/assets/909956/3232bebc-85f8-4956-9586-2a0f4ae25a12)

**Comment by sergix44** [comment]
Fixed with #6
